# f = open('text.txt','w')
# f.write('aaa')
# f.close()
# f = open('text.txt','a')
# f.write('\nbbb')
# f.close()
# f = open('text.txt','r')
# content = f.read()
# print(content)
f = open('text.txt')
# con = f.readlines()
# print(con)
f.seek(1,0)
content = f.read()
print(content)
f.close()

